name: CI

on:
  push:
    branches:
      - master
  pull_request:

env:
  TURBO_TELEMETRY_DISABLED: 1

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: setup
        uses: ./.actions/setup
        with:
          cache-key: ci-build-test
      - name: build
        run: pnpm build
      - name: test
        run: pnpm test
      - name: types
        run: pnpm check-types
