name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  TURBO_TELEMETRY_DISABLED: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: setup
        uses: ./.actions/setup
        with:
          cache-key: ci-build
      - name: build
        run: pnpm build

  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: setup
        uses: ./.actions/setup
        with:
          cache-key: ci-test
      - name: test
        run: pnpm test

  types:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: setup
        uses: ./.actions/setup
        with:
          cache-key: ci-types
      - name: types
        run: pnpm check-types
